version: '3.5'

services:
  project:
    build:
      context: './'
    volumes:
      - ./public:/var/www/html
      - ./:/var/www/
    environment:
      tz: 'Europe/Moscow'
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: surveys
      TZ: Europe/Moscow
